### PR TITLE
Use exitedAfterDisconnect instead suicide #75

### LINKED ISSUE #75: [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
A couple of references are present. I can PR the fix if you'd like.

https://github.com/godaddy/node-cluster-service/search?utf8=%E2%9C%93&q=suicide&type=

### PR DESCRIPTION
**Pull request by raphamorim**
closes #75

### CODE REVIEW

**Comment by asilvas** [comment]
Please resolve failures before I can merge. Can also update node versions for travis ci if it resolves.

**Comment by raphamorim** [comment]
Sure @asilvas. I'll update it.

**Comment by raphamorim** [comment]
Sorry for the delay @asilvas.
i've updated nodejs versions on CI. Now it's targeting `6`, `7`, `8`.

**Comment by asilvas** [comment]
published as `2.1.0` since it's a breaking change.

**Pull request merged**
