### PR TITLE
Fixes for 0.12 & IO.js compatibility

### PR DESCRIPTION
**Pull request by DullReferenceException**
* Added instructions so Travis attempts builds for Node 0.12 and IO.js.
* Fixed double-callback race conditions.
* Removed unnecessary timeouts.
* Miscellaneous code cleanup.

### CODE REVIEW

**Comment by DullReferenceException** [comment]
@asilvas: I finally have this passing on Linux as well as locally for IO.js and Node 0.12. Could you give it a look?

**Comment by asilvas** [comment]
Code looks good, however restarts during a siege result in failed requests. This might be a node 0.12 specific issue, not sure yet.

**Comment by asilvas** [comment]
+1. Verified unrelated to your changes. It appears to be related to a slight behavioral change around `server.close` where-in pending client requests are severed as well. I have some ideas how we can improve upon this outside of this PR -- only really an issue when under heavy load.

**Comment by asilvas** [comment]
Removed the guesswork on graceful web server restarts. Added test to verify operational.

**Pull request merged**
